version: "3.8"
services:
  link_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AlexLuc2000
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - database
  app:
    image: linkfilter/link-filter-api
    depends_on:
      - link_db
#    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - database

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://link_db:5432/postgres
      SPRING_DATASOURCE_USER: postgres
      SPRING_DATASOURCE_PASSWORD: AlexLuc2000
      SPRING_APPLICATION_JSON: '{
           "spring.jpa.database-platform":"org.hibernate.dialect.PostgreSQLDialect",
           "spring.datasource.driver-class-name":"org.postgresql.Driver",

           "spring.datasource.username":"postgres",
           "spring.datasource.password":"AlexLuc2000",
           "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.PostgreSQLDialect",
           "spring.jpa.generate-ddl":"true",
           "spring.jpa.hibernate.ddl-auto" : "update",
           "server.ssl.enabled": "false",

           "spring.datasource.connection-test-query":"SELECT 1",
           "spring.datasource.test-while-idle":"true",
           "spring.datasource.test-on-borrow":"true",
           "spring.datasource.validation-interval":"10000",
           "spring.datasource.log-validation-errors":"true",

           "spring.datasource.validation-query":"SELECT 1",
           "server.port":"8080"
         }'


networks:
  database:
    external: true